<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
</head>

<body>
    <header>
        <a href="<?= $requestUrl ?>"><button>Home</button></a>
        <a href="<?= $requestUrl ?>/meal"><button>Liste des Meals</button></a>
        <a href="<?= $requestUrl ?>/order"><button>Liste des Commandes</button></a>
    </header>

 <main>

    <?php include($page) ?>
 </main>
 <footer></footer>
</body>

</html>