
	<fieldset>
		<legend>Historique des commandes</legend>
		<table>
			<thead>
				<tr>
					<th>Numéro Commande</th>
					<th>Numéro User</th>
					<th>Date Création</th>
					<th>Date Succès</th>
					<th>TVA</th>
					<th>Montant TVA</th>
					<th>Total</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($orders as $order) : ?>
					<tr>
						<td>
							<?= $order['Id'] ?>
						</td>
						<td>
							<?= $order['User_Id'] ?>
						</td>
						<td>
							<?= $order['CreationTimestamp'] ?>
						</td>
						<td>
							<?= $order['CompleteTimestamp'] ?>
						</td>
						<td>
							<?= $order['TaxRate'] ?> %
						</td>
						<td>
							<?= $order['TaxAmount'] ?> €
						</td>
						<td>
							<?= $order['TotalAmount'] ?> €
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</fieldset>
	<script src="<?= $wwwUrl ?>/js/script.js"></script>
